apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails5app-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rails5app
    spec:
      containers:
      - name: rails5app
        image: crigor/rails51:v6
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rails5app-secrets
                key: database-url
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: rails5app-secrets
                key: secret-key-base