kind: Service
apiVersion: v1
metadata:
  name: rails5app-service
spec:
  selector:
    app: rails5app
  type: NodePort
  #type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000