apiVersion: v1
kind: Service
metadata:
  name: rails5app-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: rails5app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      name: http